language: python
python:
- 2.7
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
  - pip install -r requirements.txt
script:
  - python setup.py install
  - coverage run -m unittest discover ./tests/
after_sucess:
  - codecov -t CODECOV_TOKEN
  - COVERALLS_REPO_TOKEN coveralls